project:
  type: book

book:
  title: "statmemes"
  author:
    - qntkhvn
    - statsinthewild, Ph. Dizzle
  date: today
  chapters:
    - index.qmd
    - assignment.qmd
    - bonferroni.qmd
    - rsq.qmd
    - cook.qmd
    - gam.qmd
    - gradient.qmd
    - imputation.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    number-sections: false
    toc: false
    theme:
      light: flatly
      dark: darkly

execute:
  freeze: auto
